spring:
  profiles:
    active: dev
jwt:
  # 签发人
  issuer: quanxiaoha
  # 密钥
  secret: WTMpeIvbbb5MnC760XwQd+uCNfx3UfpxmWx9pI5bOlfWfoQFkqz15joj+5IUGd3cDsYhs6LMGpLZ5yXwPxWJwg==
  # token过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token请求头中的key值
  tokenHeaderKey: Authorization
  # token 请求头中的value值前缀
  tokenPrefix: Bearer
